

FROM node:alpine    
# FROM node:alpine        <-- 베이스 이미지를 도커 허브에서 가져온다.

WORKDIR /app    
# WORKDIR /app      <-- 해당 어플의 소스 코드들이 들어가게 된다.


COPY package.json ./
#COPY packge.json ./ <--- 소스코드가 바뀔때 마다 종속성까지 다시 복사해 주는 수고를

RUN  npm install
#RUN  npm install <--- package.json에 명시된 종속성을 다운받는다.

COPY ./ ./ 
# COPY ./ ./    <--- 이제 모든 소스코드들을 WORKDIR로 복사해준다.

CMD ["npm", "run", "start"]
# CMD ["npm", "run", "start"] <<---- 이 컨테이너가 실행될 때 같이 실행할 명령어를 지정해준다.


